table Planilha1
	lineageTag: 0379c966-48d0-434c-830d-ef842a8220a1

	column Column1
		dataType: string
		lineageTag: d1f248e1-1357-4226-81b3-4df5c39d30fc
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: d8d206ec-543e-4e2b-8780-75fb60e96746
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 0554ec9e-0aa6-4112-936b-50342f92374c
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: a9ca2daf-7a9f-496f-8072-23aca0e99267
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 76748015-8f84-42e5-a5dc-d674dd8c6099
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 6004e7e2-d461-4ac6-beb0-ccbe771f0a29
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 6b512a18-3d69-4ab0-a8fe-7bbfda76c315
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: c6e8a14e-84b4-4d3d-91db-ef43438830ac
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 5ee796e1-3192-432b-a988-889ecf403213
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: dcd01f26-9e0d-4648-a0aa-f91fb7cb88d6
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: c5e5c1fa-4443-416d-8dca-2a134efb56ec
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 043b363a-1942-4c29-b817-91f6c4751942
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 5990cbea-d98f-4219-a15f-82779c274b4d
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 4568c2c2-2c8e-41ec-8b74-c5d60c83618b
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 539bf47a-714d-4fee-a17c-013bdacdb881
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 865bf8bf-486e-4d16-ae28-5a393332dca2
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 7fe81a41-98be-4bbc-b7b6-bfd418419d1e
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	partition Planilha1 = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\leona\OneDrive\Área de Trabalho\code\PBI GIT\Poc_git_pbi\plano_contencao_de_gastos.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Planilha1_Sheet,{{"Column1", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

